import { chromium } from 'playwright';
process.env.FIRESTORE_EMULATOR_HOST='127.0.0.1:8080';process.env.FIREBASE_AUTH_EMULATOR_HOST='127.0.0.1:9099';process.env.GCLOUD_PROJECT='parbaughs';
const admin=(await import('firebase-admin')).default; if(!admin.apps.length) admin.initializeApp({projectId:'parbaughs'});
const token=await admin.auth().createCustomToken('test_zach_uid_01');
const b=await chromium.launch();const ctx=await b.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:2});const page=await ctx.newPage();
const errs=[];page.on('console',m=>{if(m.type()==='error')errs.push(m.text().slice(0,120))});page.on('pageerror',e=>errs.push('PAGEERR:'+e.message.slice(0,100)));
await page.addInitScript(()=>{try{localStorage.setItem('pb_clubhouse_welcomed','1')}catch(e){}});
await page.goto('http://localhost:5173/?emulator=1');
await page.waitForFunction(()=>typeof window.auth!=='undefined'&&window._pbEmulator===true,{timeout:12000});
await page.evaluate(async t=>{await window.auth.signInWithCustomToken(t)},token);
await page.waitForFunction(()=>!document.getElementById('mainApp')?.classList.contains('hidden'),{timeout:15000});
await page.evaluate(()=>Router.go('rounds'));await page.waitForTimeout(1500);
await page.evaluate(()=>Router.go('home'));await page.waitForTimeout(1800);
await page.evaluate(()=>window.scrollTo(0,0));
await page.screenshot({path:'.claude/state/wave6/mobile-home-nemesis.png',fullPage:false});
const info=await page.evaluate(()=>({chip:!!document.querySelector('.hm-nemesis'),txt:(document.querySelector('.hm-nemesis__txt')||{}).textContent||''}));
console.log(`chip=${info.chip} txt="${info.txt}"${errs.length?' ERR:'+errs.slice(0,2).join(' | '):''}`);
await b.close();
