import { chromium } from 'playwright';
import { readFileSync, writeFileSync } from 'fs';
const names=['01-white-rose','02-rose-flagsticks','03-rose-shield','04-rose-seal','05-keystone-rose','06-rose-monogram','07-heritage-star','08-rose-ball'];
const labels=['1 · White Rose','2 · Rose + flagsticks','3 · Rose shield','4 · Rose seal','5 · Keystone + rose','6 · Rose monogram','7 · Heritage star','8 · Rose-ball'];
const imgs=names.map(n=>readFileSync('public/img/gen/logos2/'+n+'.png').toString('base64'));
const b=await chromium.launch();
const cell=300,cols=4,lab=26,W=cols*cell,H=2*(cell+lab);
const pg=await b.newPage({viewport:{width:W,height:H}});
await pg.setContent('<body style="margin:0"><canvas id="c" width="'+W+'" height="'+H+'"></canvas></body>');
await pg.evaluate(async ({imgs,labels,cell,cols,lab})=>{const c=document.getElementById('c'),x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,c.width,c.height);for(let i=0;i<imgs.length;i++){const im=new Image();im.src='data:image/png;base64,'+imgs[i];await im.decode();const col=i%cols,row=Math.floor(i/cols),ox=col*cell,oy=row*(cell+lab);x.drawImage(im,ox,oy,cell,cell);x.fillStyle='#14130f';x.font='600 13px Georgia,serif';x.textAlign='center';x.fillText(labels[i],ox+cell/2,oy+cell+18);x.strokeStyle='#ddd';x.strokeRect(ox,oy,cell,cell);}},{imgs,labels,cell,cols,lab});
writeFileSync('public/img/gen/logos2/_montage.png',Buffer.from(await pg.evaluate(()=>document.getElementById('c').toDataURL('image/png').split(',')[1]),'base64'));
await b.close();console.log('montage2 done');
