#!/bin/bash
# cron-proactive.sh — Proactive cycle invocation wrapper.
# Per HEADLESS_OPERATION_PROTOCOL § 5 + PROACTIVE_IMPROVEMENT_PROTOCOL.md
#
# Activities (in order):
#   1. Bug pattern analysis — Lane 2 (20k tokens)
#   2. UI polish scan — Lane 1 (30k tokens)
#   3. Performance optimization scan — Lane 3 (25k tokens)
#   4. Design system extension scan — Lane 4 (20k tokens)
#   5. Proposal queue assembly + Critic quality-bar pre-review (15k tokens)
#   6. State persistence + cycle close (10k tokens)
#
# Budget: 120k tokens / 90 min
#
# CRITICAL: This cycle generates PROPOSALS ONLY. No implementation.

set -e

CYCLE_ID="proactive-$(date -u +%Y%m%d-%H%M)"
JOURNAL="docs/agents/SESSION_JOURNAL.md"
QUEUE_FILE=".claude/state/proactive-proposals/$(date -u +%Y-%m-%d).md"
TOKEN_CAP="${CYCLE_TOKEN_CAP:-120000}"
DURATION_CAP="${CYCLE_DURATION_CAP:-5400}"
START_TIME=$(date -u +%s)

mkdir -p .claude/state/proactive-proposals

# Cycle start journal entry
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [PROACTIVE-CYCLE-START] cycle_id=$CYCLE_ID. Lock acquired." >> "$JOURNAL"

# Pre-flight: check emergency-halt
if [ -f .claude/state/emergency-halt.json ]; then
    echo "Emergency halt detected. Exiting cycle."
    echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [EMERGENCY-HALT-DETECTED] cycle_id=$CYCLE_ID. Emergency halt active. Exiting." >> "$JOURNAL"
    exit 0
fi

# Pre-flight: detect approved-but-unimplemented proposals from prior weeks
APPROVED_PENDING_COUNT=0
if [ -d .claude/state/proactive-proposals ]; then
    for prior_queue in .claude/state/proactive-proposals/*.md; do
        if [ -f "$prior_queue" ] && [ "$prior_queue" != "$QUEUE_FILE" ]; then
            PRIOR_APPROVED=$(grep -c "^\*\*Founder decision:\*\* Accept" "$prior_queue" 2>/dev/null || echo "0")
            PRIOR_IMPLEMENTED=$(grep -c "^\*\*Implemented at:\*\*" "$prior_queue" 2>/dev/null || echo "0")
            APPROVED_PENDING_COUNT=$((APPROVED_PENDING_COUNT + PRIOR_APPROVED - PRIOR_IMPLEMENTED))
        fi
    done
fi

echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [PROACTIVE-PREFLIGHT] cycle_id=$CYCLE_ID. Approved-but-unimplemented from prior weeks: ${APPROVED_PENDING_COUNT}." >> "$JOURNAL"

# Initialize proposal queue file
cat > "$QUEUE_FILE" <<EOF
# Proactive Proposal Queue — $(date -u +%Y-%m-%d)

**Generated by:** Proactive cycle (weekly)
**Cycle ID:** $CYCLE_ID
**Generation started:** $(date -u +%Y-%m-%dT%H:%M:%SZ)

**Review deadline:** $(date -u -d "+14 days" +%Y-%m-%d 2>/dev/null || date -u -v+14d +%Y-%m-%d) (proposals auto-flag stale after this)

---

## Summary

_Populated at cycle end._

---

## Lane 1 — UI Polish

_Proposals populated by proactive cycle Claude Code invocation._

## Lane 2 — Bug Discovery

_Proposals populated by proactive cycle Claude Code invocation._

## Lane 3 — Performance

_Proposals populated by proactive cycle Claude Code invocation._

## Lane 4 — Design System Extension

_Proposals populated by proactive cycle Claude Code invocation._

---

## Implementation tracking

| Proposal ID | Founder decision | Decision date | Implemented at | Notes |
|---|---|---|---|---|

---

## Cycle metadata

- **Cycle ID:** $CYCLE_ID
- **Token cap:** $TOKEN_CAP
- **Duration cap:** ${DURATION_CAP}s

EOF

# ===============================================================================
# CLAUDE CODE INVOCATION SECTION
# ===============================================================================
# The actual proactive work happens via Claude Code CLI invocation here.
# Founder configures this section based on their Claude Code setup.
#
# Recommended pattern:
#   claude-code run \
#     --prompt-file .claude/prompts/proactive-cycle.md \
#     --token-cap "$TOKEN_CAP" \
#     --working-dir . \
#     --state-dir .claude/state/ \
#     --queue-file "$QUEUE_FILE" \
#     --halt-on-budget-90 true \
#     --halt-on-emergency-file .claude/state/emergency-halt.json
#
# The prompt file (.claude/prompts/proactive-cycle.md) instructs Claude Code to:
#   - Read PROACTIVE_IMPROVEMENT_PROTOCOL.md for lane definitions
#   - Read parbaughs-proactive-proposal skill for generation pattern
#   - Execute activities 1-6 in order with respective token budgets
#   - Run Critic quality-bar pre-review on every proposal
#   - Reject vague/speculative/out-of-scope proposals pre-queue
#   - Apply HALT item 19 if scope violation detected (convert to FIQ instead)
#   - Respect budget watchdog at 90%/100% thresholds
#   - Write proposals to queue file per template
#   - Emit cycle outcome summary at end
# ===============================================================================

# Placeholder: replace with actual Claude Code invocation per § 7 of CRON_CONFIGURATION.md
echo "Proactive cycle invocation pending Claude Code CLI configuration."
echo "Configure .claude/scripts/cron-proactive.sh per CRON_CONFIGURATION.md § 7."

# Calculate cycle duration
END_TIME=$(date -u +%s)
DURATION=$((END_TIME - START_TIME))
DURATION_MIN=$((DURATION / 60))

# Update cycle history
mkdir -p .claude/state
if [ ! -f .claude/state/cycle-history.json ]; then
    echo '{"cycles":[]}' > .claude/state/cycle-history.json
fi

TEMP_HISTORY=$(mktemp)
jq --arg cid "$CYCLE_ID" \
   --arg start "$(date -u -d @$START_TIME +%Y-%m-%dT%H:%M:%SZ 2>/dev/null || date -u -r $START_TIME +%Y-%m-%dT%H:%M:%SZ)" \
   --arg end "$(date -u +%Y-%m-%dT%H:%M:%SZ)" \
   --arg dur "$DURATION" \
   '.cycles += [{
       "cycle_id": $cid,
       "type": "proactive",
       "started_at": $start,
       "ended_at": $end,
       "duration_seconds": ($dur | tonumber),
       "tokens_consumed": 0,
       "outcome": "PLACEHOLDER",
       "summary": "Proactive cycle invocation not yet configured"
   }]' .claude/state/cycle-history.json > "$TEMP_HISTORY"
mv "$TEMP_HISTORY" .claude/state/cycle-history.json

# Cycle end journal entry
echo "[$(date -u +%Y-%m-%dT%H:%M:%SZ)] [PROACTIVE-CYCLE-END] cycle_id=$CYCLE_ID. Duration: ${DURATION_MIN}m. Outcome: PLACEHOLDER (Claude Code invocation pending configuration)." >> "$JOURNAL"

echo "Proactive cycle complete: $CYCLE_ID (${DURATION_MIN}m). Queue: $QUEUE_FILE"
