// ========== THE CADDY NOTES ==========
Router.register("caddynotes", function() {
  var h = '<div class="sh"><h2>The Caddy Notes</h2><button class="back" onclick="Router.back(\'home\')">← Back</button></div>';

  h += '<div style="text-align:center;padding:16px"><div style="margin-bottom:6px"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" width="28" height="28" style="color:var(--gold)"><path d="M16 4h2a2 2 0 012 2v14a2 2 0 01-2 2H6a2 2 0 01-2-2V6a2 2 0 012-2h2"/><rect x="8" y="2" width="8" height="4" rx="1"/></svg></div>';
  h += '<div style="font-family:var(--font-display);font-size:18px;color:var(--gold)">The Caddy Notes</div>';
  h += '<div style="font-size:11px;color:var(--muted);margin-top:4px">What\'s new, what\'s fixed, and what\'s coming</div>';
  h += '<div style="font-size:10px;color:var(--gold);margin-top:6px;font-weight:600">v' + APP_VERSION + '</div></div>';

  function tagColorFor(tag) {
    return tag === "NEW" ? "var(--birdie)" : tag === "FEATURE" ? "var(--birdie)" : tag === "FIXED" ? "var(--gold)" : tag === "IMPROVED" ? "var(--blue)" : tag === "INFRA" ? "var(--cb-mute)" : "var(--muted)";
  }
  function renderEntry(r) {
    var tc = tagColorFor(r.tag);
    return '<div style="padding:4px 0;display:flex;gap:8px;align-items:flex-start">' +
      '<span style="font-size:8px;font-weight:700;color:' + tc + ';background:' + tc + '15;padding:2px 6px;border-radius:3px;flex-shrink:0;margin-top:2px">' + r.tag + '</span>' +
      '<span>' + r.item + '</span></div>';
  }

  // Current Release
  h += '<div class="section"><div class="sec-head"><span class="sec-title" style="color:var(--birdie)">What\'s New · v' + APP_VERSION + '</span></div>';
  h += '<div style="font-size:10px;color:var(--muted);padding:0 16px 8px">June 2026 · The polish pass</div>';
  h += '<div class="card"><div class="card-body" style="font-size:12px;color:var(--cream);line-height:1.8">';
  var currentNotes = [
    { item: "A few corners of the Clubhouse that used to sit empty now greet you instead. Your home page's rivalry line no longer disappears when you haven't built a rivalry yet — it invites you to start one (play the same course, same day as another Parbaugh and the Caddy starts keeping the tape). The season Standings, before anyone's teed off, now show a proper 'blank scorecard' card daring you to set the pace rather than a bare line. And a course's Legend crown now appears as soon as someone's logged a round there — the first regular on the board — instead of staying hidden until two. Quiet weeks should still feel like the club, not a broken page.", tag: "IMPROVED" },
    { item: "Your Feed gained a second way to salute a round. Alongside Kudos there's now a Tee Tap — golf's own nod of respect, the one you give across the green when somebody stripes one. Tap the little brass tee on any round and it lights up gold with a running count, so a good score can collect both the heart and the hat-tip. Kudos says nice; a Tee Tap says well played. (And a quiet bit behind it: blocking a member now holds at the server too — a blocked golfer can no longer slide a comment or a message your way, not just have it hidden on your screen.)", tag: "NEW" },
    { item: "The Trophy Room now keeps a Roll of Honor — a running chain of every season's champion, the reigning name lit at the top of the lineage with their points, and the Caddy daring the next challenger. As the seasons stack up it becomes the club's own record book of who held the crown, and when.", tag: "NEW" },
    { item: "Every course now crowns a Course Legend — and it isn't who scores lowest, it's who shows up most. Whoever's logged the most rounds at a course over the last 90 days wears the laurel on that course's page, with a line on who's chasing ('testNick needs 2 more to take it'). It's the Clubhouse rewarding the regulars: the weekend warrior who's always out there can hold a crown the ringer never will.", tag: "NEW" },
    { item: "A quiet bit of housekeeping behind this week's new features: the app now fully escapes member names and course text everywhere they appear, closing a small text-injection gap so a cleverly-named profile can never break a page. And the Caddy's Round of the Week now only crowns full eighteen-hole rounds, so a half-round can't sneak off with the title.", tag: "FIXED" },
    { item: "Every week the Caddy now files a report. At the very top of the Feed sits a fresh dispatch — 'The Caddy's Report · Week of {date}' — that reads the week's rounds and calls out who did what: the Round of the Week, the Grinder who logged the most, the Hot Hand who beat his average, and the occasional Sandbagger Watch (all in good fun). It's the club's own little newsletter, written about you and the boys, refreshing as the week plays out. A quiet week says so honestly rather than making something up.", tag: "NEW" },
    { item: "Your Feed now reads like the club's front page. Instead of every round landing as one more identical row, the most newsworthy round of the moment is set as a proper lead story up top — an oversize headline in the Clubhouse's own type, the score called out large, and the Caddy's take pulled out as a quote beside a brass rule ('That wasn't a round of golf, it was a nature walk with anger issues') — with the rest of the day's rounds running beneath it like columns under a banner. And when two of you played the same course on the same day, that round card now wears a small H2H tag that taps straight through to your head-to-head tape. The feed stopped being a list and became an issue.", tag: "IMPROVED" },
    { item: "Your profile now names your nemesis. Every time you and another Parbaugh play the same course on the same day, the app has quietly kept a head-to-head record — and it now surfaces the rival you've crossed most as a card right at the top of your profile: their face, your lifetime record in big record-book numerals, and a line from the Caddy on where it stands ('You've got testKayvan's number — 3–0, but he's lurking'). Your other rivalries sit just beneath, and on a wider screen your home greeting drops a one-line reminder of the grudge. The numbers were always there; now someone's keeping count out loud.", tag: "NEW" },
    { item: "The Standings now open on the race you're actually in. Above the full board sits a new band — The Chase — that frames the title fight at the top, then turns to your own tug-of-war: the member one rung above you and the one right below, the exact points between you, and a word from the Caddy on where you stand ('You sit 4th. testNick is +5 ahead — one good round flips it; Marco is 2 back, breathing down your neck'). The season stops being a flat list of names and becomes a plot with you in it.", tag: "NEW" },
    { item: "The faintest text on a few busy pages got the same care. The small print on your calendar — the day labels, the event details, the lines that tell you what's on the books — along with the section labels in Settings and the steps in the first-run welcome, had been set in the very lightest gray and were hard to read against the cream. They now read in the same comfortable, slightly deeper tone as the rest of the quiet text, so nothing on those pages fades out from under you.", tag: "IMPROVED" },
    { item: "The quieter lines of text all through the Clubhouse — the small descriptions under each item on the More menu, the timestamps and details on your rounds and the feed, the labels beneath your stats — were set in a soft gray that sat a touch too light against the cream to read easily at a glance. They have all been deepened a shade so they are comfortable to read, while staying clearly secondary to the headings above them. Nothing moved; the quiet text just got easier on the eye everywhere.", tag: "IMPROVED" },
    { item: "The small labels over each award on the Season Recap, like Low Round of the Season and Grinder Award, got the same darkening the rest of the awards just received, so they now read clearly in a deeper brass rather than fading into the card.", tag: "IMPROVED" },
    { item: "A few quiet bits of writing around the Clubhouse were fainter than they ought to be. The \"What's on your mind?\" prompt that opens a feed post, the small print under each setting that explains what it does, and the little labels above each award on Awards Night, like Round of the Year, were all lettered a touch too pale against the cream, so they faded into the page right where you wanted to read them. Each has been darkened to sit clearly and comfortably on the eye, the award labels now in a richer, deeper brass. Nothing moved and nothing changed but the ink; it's simply easier to read now.", tag: "IMPROVED" },
    { item: "The first time you open the refreshed Clubhouse, the quiet welcome-back note that greets you has been given the same care as everything behind it. It used to slide up in pale lettering on gold that was hard to read at a glance, and it sat pressed right against the row of buttons along the bottom of your screen. It now arrives as a small deep-felt card lifted clear of that row, Welcome back lettered in brass above a line letting you know the look has been refreshed and your rounds and ParCoins are safe. It shows once and then steps aside. A small thing, but it's the very first thing you see of the new Clubhouse, so it ought to look the part.", tag: "IMPROVED" },
    { item: "The front door has been given its last coat of polish. The sign-in screen already opened on the Clubhouse's deep green, but the green lay flat, the same shade corner to corner. It now has real depth to it: a warm pool of brass light glows up behind the club badge as though a lamp were lit over the door, the green deepens toward felt at the edges so the whole screen draws your eye inward to your sign-in, and the cream card itself now rests above it all with a brighter top edge and a deeper shadow, the way a card laid on a table sits above the cloth. The Sign In button picks up the same care, a soft brass sheen across its face and a quiet glow beneath it, so the one thing to tap plainly looks worth tapping. Nothing about signing in has changed; the doorway you do it through just finally looks finished.", tag: "IMPROVED" },
    { item: "The two doors you walk through most now carry a little more polish. The Start a round button on your phone's home, the one resting in the green panel on a day with no round going, used to read in quiet cream that nearly settled into the felt behind it. It now wears the Clubhouse's own brass, so the single most useful thing to tap is plainly the brightest thing on the page. And the sign-in screen no longer just appears all at once: the club badge, the Parbaughs name, and your sign-in card now ease up into place one after another as the front door opens, a small, unhurried sense of arrival before you've tapped a thing.", tag: "IMPROVED" },
    { item: "Moving around the Clubhouse feels smoother now. Tapping from one part of the app to another used to snap straight to the next screen with no motion at all, like a slide clicking forward. Each page now eases in as you arrive, lifting gently into place with a soft fade, and stepping back settles in from the other direction so it always feels like you're returning the way you came. The bigger arrivals, walking onto Play Now or coming off a finished round, get a quiet brass line that sweeps across the top as the screen settles. It's the kind of thing you feel more than you notice, and it makes the whole app move like one finished piece rather than a stack of separate pages.", tag: "IMPROVED" },
    { item: "The way into the Clubhouse has been rebuilt to feel like arriving at your own club. The sign-in screen used to open on a flat tan page with a plain form floating in the middle of it, the very first thing anyone saw and the least finished of everything. It now opens on a deep billiard-green threshold, the Parbaughs name lettered large in gold above a quiet Members Only, with your sign-in resting on a clean raised cream card below, the way the rest of the Clubhouse already reads. Joining with an invite code and resetting a password wear that same handsome card. Whether you're signing in, creating your account, or coming back to reset a password, the front door now speaks the same language as everything waiting inside.", tag: "IMPROVED" },
    { item: "On your phone, the Clubhouse home now reads like the rest of the app instead of a plainer cousin of it. When there's no round going, it opens on a deep billiard-green panel that says the Clubhouse is ready when you are, with a clean cream Start a round button sitting right in it, so the most important thing to tap is the most obvious thing on the page. And your three figures just below, your rounds, your handicap, and your best, no longer float as three flat little cards; they now sit together in one handsome band ruled top and bottom in brass, your numbers lettered large in the Clubhouse's own record-book type, exactly the way your finished rounds and the season standings already read. Your home finally speaks the same language as everywhere else you look.", tag: "IMPROVED" },
    { item: "Every card in the Clubhouse lifts a little more cleanly now. The pages behind your stats, your rounds, your standings, and the pro shop sit a shade deeper, so each panel rests on the cream like a card laid on a table, carrying a soft, honest shadow rather than lying flat against it. Brush a card you can tap and it rises to meet you instead of going dim. And on the Standings, the season archive that runs down the page, each past season beside its champion, now lines up to the same clean margin as everything above it, so a long champion's name no longer crowds the right edge.", tag: "IMPROVED" },
    { item: "The little example ideas that show before you've started anything, the wager and bounty suggestions, the sample matches on Challenges, and the example tee times, used to sit inside faint dashed outlines that made them look like unfinished placeholders. Each one now rests on its own clean raised row with a small brass dot and crisp, readable text, so they read as real suggestions worth a tap. The quiet empty pages on Courses, Find Players, and Party Games got the same care: instead of a dashed box, each now sits on a soft raised panel that lifts off the page the way the rest of the Clubhouse already does.", tag: "IMPROVED" },
    { item: "The Start a round screen now sits on a proper card. Where you choose your course, your format, and how many holes you're playing used to lie flat against the page, the fields washing into the same cream behind them so the whole screen felt half finished. Those choices now rest together on a clean raised sheet that lifts off the page with a soft, honest shadow, the way your home and your courses already do, each field a crisp recessed well with the Tee it up button anchored beneath them. Setting up a round finally looks like the rest of the Clubhouse.", tag: "IMPROVED" },
    { item: "Your Clubhouse home has real depth to it now, and a clear front door. The page behind everything sits a shade deeper, so your stats and the league's pulse lift off it like cards laid on a table, each carrying a soft, honest shadow instead of lying flat against the same cream. And on a day with no round going, the home now opens on a deep billiard-green panel that says the Clubhouse is ready when you are, with a clean cream Start a round button sitting right in it, so there is always one handsome, obvious place to begin. Your very first round gets the same treatment: the card that starts you off wears that same green, so the most important thing to tap is the most obvious thing on the page.", tag: "IMPROVED" },
    { item: "The Parbaughs mark you save to your home screen has been redrawn to sit crisp at every size. However you keep the app, tucked in a folder, filling a tile on a tablet, or sitting in your dock, the club's badge now renders sharp and clean rather than stretched from a single picture, and on Android it settles properly into whatever shape your phone gives its icons.", tag: "IMPROVED" },
    { item: "Your league can now mint its own silverware. Whoever runs your league can compose a custom trophy right inside the app: give it a name, choose its emblem from the Clubhouse's own set or bring your own, mark it common, rare, or championship, and tell it what to chase, the most birdies, the lowest round, the most pars in a season, or the longest run of weeks with a round to its name. Once it's saved it takes its place in everyone's Trophy Room beside the standing badges, and the ones tracking a live race show up on the Standings with whoever's leading it right now. A trophy that hasn't seen a qualifying round yet says so plainly rather than crowning no one, so every name on the wall is one that's truly been won.", tag: "NEW" },
    { item: "Play any course three times with your full hole-by-hole scores and a heat map of that course now appears on your Rounds page, and again on your profile. Your card is laid out as a tile for every hole you played: the holes you tend to play under par sit in a quiet fairway green, the ones you usually par stay calm and neutral, and the holes that keep costing you shots show in claret red. Each tile marks the hole and how your scoring there averages out against par, and a tap opens it up: your average on that hole, your best and worst, whether you've been steady or streaky there, and every round you've played it. A line beneath sums up your rounds at the course, your scoring average, your best round there, and the single hole that's been toughest on you. Until you've logged three full rounds at a place, the spot holds a friendly note showing how close you are, counting only the rounds where you marked every hole, since a heat map needs the whole card to draw.", tag: "NEW" },
    { item: "Opening one of your finished rounds now reads like a page from the club's own record book. A completed round used to show little more than a bare score, and a round you reached from a shared link only told you the full detail was still coming. It now opens properly: your course and your score lettered large up top, a quiet line tallying your eagles, birdies, pars, and putts, and then the whole round laid out hole by hole, your par across the top and your score beneath it, every number tinted so an eagle glows brass, a birdie reads green, and a bogey or worse shows in claret. Below the card, By the numbers gives you your score to par alongside your fairways, greens, and putts at a glance; the group's commentary and the Caddy's take thread in beneath; and your scorecard photo, your story, and the image you save to share all settle into one clean column. Tap a friend's shared round and it now opens to this same full page rather than a placeholder.", tag: "IMPROVED" },
    { item: "Your profile has been rebuilt to read like the rest of the Clubhouse. It used to open with everything stacked down the middle, your photo, your name, and your details all centered over a page that stretched thin on a wider screen. It now opens with a proper portrait: your photo to the left, still wearing whatever ring you've equipped, with your name lettered large in the Clubhouse's own type beside it, the title you carry and the year you joined in a quiet line above, your real name just below, and your badges in a clean row. Your level rides on your photo, your bio reads in the Clubhouse's hand, and Share Profile Card sits right where you'd reach for it. Everything below, your standing, your Parcoins, your stats, and your rounds, now settles into one comfortable column instead of spreading across the whole screen, so your profile reads the same handsome way on a phone or a desktop.", tag: "IMPROVED" },
    { item: "The very first time you open Parbaughs, the welcome has been rebuilt into a proper arrival. Instead of a plain card sitting on the same cream as everything else, the screen now opens full, with a deep billiard-green panel down one side carrying the Parbaughs name and a quiet line of its own, and your welcome lettered large on the cream beside it. A slim brass bar across the top fills as you move through the short cards that introduce the league, scoring, the seasons, ParCoins, and the legacy you're starting, and then you land on setting up your profile: your photo, your name, your usual scoring range, your home course, and a short bio, all in the same clean fields the rest of the app now uses. It reads less like a form to clear and more like being shown into the clubhouse for the first time.", tag: "IMPROVED" },
    { item: "The tools the commissioner uses to run a league have been rebuilt to match the rest of the Clubhouse. The page that handles members, invites, feature requests, and the league's housekeeping now opens with a plain headline, Admin, and reads in the same clean, lettered sections as everywhere else, with a slim index down the side on a wider screen to jump straight to what you need. Most of you will never need it, but whoever keeps your league running now works from a calmer, clearer desk.", tag: "IMPROVED" },
    { item: "Your Settings have been rebuilt to read like the rest of the Clubhouse. The page now opens with a plain headline, Settings, over a quiet line noting how long you've been a member, and on a wider screen a slim index runs down the side so you can jump straight to the part you want, with your place in it lit in brass as you scroll. Everything sits in clean, lettered sections rather than one long run: your account and sign-in, where your weather location comes from, your notifications, how the app looks, your privacy and anyone you've blocked, your Parcoin balance, the tools you use to run a league, your backups, and an about page with the version and the legal notes. The look picker now shows all six Clubhouse themes as little swatches so you can see each one at a glance, the switches for a public profile and sunlight mode read clearly as on or off, and on a phone the whole thing simply stacks into one easy column.", tag: "IMPROVED" },
    { item: "Your leagues now read like the front page of the club. The page opens with a plain headline, my leagues, over a quiet count of how many you're in, and each league you belong to sits as a clean card showing its name, how many play there, the year it was founded, and whether it's open or invite-only, with the one you're currently in marked in brass. Open any league and its own page lays the commissioner across the top beside the same handsome count of members, the founding year, and how it's accessed, then the invite code to share, and, if you run the place, the full roster, any pending requests to join, your settings, and the controls to manage it all. Below your own leagues, a Discover row shows the public clubhouses you could ask to join. And the very first time you arrive without a league, the page greets you as a Lone Wolf with three clear ways in: start your own crew, drop in an invite code, or browse the open clubhouses already underway.", tag: "IMPROVED" },
    { item: "Posting to the feed now opens a proper writing space instead of a single cramped line. Tap \"What's on your mind?\" and a clean composer slides in that reads like club stationery: a roomy sheet with a brass cursor, and a quiet count in the corner showing how many characters you have left, which warns you in brass as you near the end and turns claret if you run past it. A small switch up top lets you aim your post at your league, with a place held for the wider community as that feed opens up. Your league post lands in the feed the moment you tap Post, just as before. Step away mid-thought and your words are waiting when you reopen it; on a keyboard, Command or Control with Enter sends, and Escape closes.", tag: "IMPROVED" },
    { item: "Your feed has been rebuilt to read like the club's own morning paper. It opens with a plain headline, what's happening, over your league's name and a quiet line counting the day's posts. Each round now shows up as a clean card: who played and how long ago, the score in big brass figures with how it stood against par, the course and the tees, a row of dots tracking every hole, and the numbers that matter, your front and back nine, fairways, greens, and putts, with one of the Caddy's dry one-liners underneath. You can tip your Kudos, reply, open the full scorecard, or share without leaving the page, and the clubhouse chatter threads in right alongside the rounds. As you scroll, quiet headers like Today and Yesterday mark where each day begins, and a League tab keeps it to your group while Community looks across the platform. The box up top is ready whenever you've got something to say.", tag: "IMPROVED" },
    { item: "Your Trophy Room has been rebuilt to read like a proper trophy case. The page now opens with your name in the Clubhouse's own lettering over a simple headline, your hardware, with a quiet line beneath counting your level, your trophies, and your aces. Just below, your standing sits in one clean panel: your level in big brass figures, the title you carry, a slim bar showing how close you are to the next level, and a plain line telling you how much more play it takes to get there. Your most recent trophies are called out first, then a short list of your records: your best round, your rounds logged, the courses you've played, and your holes-in-one, which taps straight through to the Ace Wall. Below that, the full wall shows every badge there is to earn. The ones you've won sit lit with a soft brass glow, the rest wait as quiet slots, and a single tap on Earned only narrows it to what you've already got. The title ladder at the bottom lays out all twenty ranks from Rookie to G.O.A.T., with the one you wear now marked in brass.", tag: "IMPROVED" },
    { item: "Your scheduling calendar has been rebuilt to read like a proper datebook. The month and year now crown the page in the Clubhouse's own lettering, with a quiet line beneath that counts what's actually on the books, how many events are scheduled and how many rounds you've logged this month. You can keep the familiar month grid, where today is marked in brass and each day shows what's planned at a glance, or flip to a clean List view that lays your upcoming tee times, trips, and rounds out in order. Tap any day to open the full detail: the tee time and who's in, the trip and the courses it plays, the rounds posted and how everyone fared against par. A month with nothing on it now says so plainly and points you to add the first thing, rather than sitting blank, and the scheduling chat for sorting out next week's round is right there at the bottom.", tag: "IMPROVED" },
    { item: "Your Parcoin shop has been rebuilt to feel like the pro shop at your club. Your balance now sits up top as one big, handsome figure, with a quiet line beneath it counting everything you've earned all-time, and just below that a running list of your recent activity reads at a glance: what you won, spent, and earned, with a week of daily logins folded into a single tidy line instead of repeating down the page. The cosmetics themselves, the rings, banners, card skins, name effects, and titles, now sit in clean tiles that show a live preview on your own name and photo, and the one you've equipped is marked in brass. At the bottom, four cards point you straight to the places you put those coins to work: Wagers, Bounties, Challenges, and the Rich List.", tag: "IMPROVED" },
    { item: "The screen you score on during a round has been rebuilt to feel like your own clubhouse. Your stroke count now sits front and center as one big, handsome figure, with its name, Birdie, Par, Bogey, called out right beneath it, and the plus and minus buttons on either side are sized for a thumb. A quiet line above it names the hole with its par, yardage, and stroke index, and a row of markers tracks every hole at a glance. On a larger screen, your full card now rides alongside so you can read the whole round while you enter the next number. And a hole you haven't scored yet simply invites you to tap, rather than sitting blank.", tag: "IMPROVED" },
    { item: "The top of your Clubhouse home reads cleaner still. The green welcome panel used to carry a small line, \"The Parbaughs · Clubhouse,\" tucked right above your greeting, echoing the masthead that already crowns the page, so the same name met you twice before you reached anything useful. That line is gone, and the panel now opens straight with your greeting and your latest round. Just below, on the season ladder, whoever sits in first now stands out in gold, their place and their points lettered in the Clubhouse's own brass, so one glance tells you who is leading the season. And the very first time a new member walks in, the welcome no longer repeats the banner above it; it now tells them how many of you are already here and how many courses have been played, then points them to their first round.", tag: "IMPROVED" },
    { item: "Your Clubhouse home now opens on a proper scoreboard. The greeting at the top, your name and the time of day, used to sit as plain text on the same cream as everything below it, so the page had no clear front door. It now rests on a deep billiard-green panel with a soft brass edge and your name lettered in gold, and your latest round is called out right beneath it in big clean figures. It is the first thing you see when you walk in, and it finally feels like stepping up to the first tee at your own club.", tag: "IMPROVED" },
    { item: "Sending a direct message on your phone feels right now. The box where you type used to slip down behind the menu bar at the bottom of the screen, so on a longer note you could lose sight of what you were writing, and tapping into it would jump the whole page in for a beat. The message box now rests clearly above the menu where your thumb expects it, and typing no longer zooms the page. Your list of conversations reads cleaner too, with the time, the New mark, and each last message sized to scan at a glance.", tag: "FIXED" },
    { item: "The scheduling calendar now speaks one language in color. Each kind of plan keeps a single shade, from the button that creates it to the dot on the day: events in gold, tee times in claret red, range days in slate blue, and rounds in the Clubhouse's own fairway green. Before, a tee time was gold on its button but red on the calendar, an event flipped between green and gold, and rounds wore a bright lime that matched nothing else. Today is now simply lit in gold so you can always find your place, rather than carrying a green dot that looked almost exactly like a round, and the small key beneath the grid lines up with all of it.", tag: "IMPROVED" },
    { item: "When you set up a wager, the six bet types now show proper little symbols instead of single letters. Stroke Play, Best 9, Most Pars, Fewest Putts, Nassau, and Beat Their Score each used to sit behind a lone initial, so a plain \"T\" stood in for Fewest Putts and you had to read the label to be sure which was which. Each one now wears a clean drawn icon, matching the crisp symbols the rest of the app already uses, so the choices read at a glance and the same little mark rides along on your wager cards.", tag: "IMPROVED" },
    { item: "A nine-hole round now reads honestly against par everywhere. When you posted nine holes, a few screens were still comparing your score to a full eighteen-hole par, so a good nine could show up green and under par as if you'd gone around all eighteen. Now your rounds list, a round's own page, a member's profile, the calendar, the feed, and the image you save all measure a nine against nine. A 56 on the front nine reads as the +20 it really is, not a flattering minus sixteen.", tag: "FIXED" },
    { item: "The Start a round screen opens cleaner now. The page already titles itself \"Play now,\" but it used to repeat that with a second \"Start a round\" heading right below, so you met two titles stacked together before you got to anything useful. That extra heading is gone. The short line telling you how it works, score hole by hole as you play, now sits quietly under the title, and the link to start a Scramble round instead is right there in the same breath. One clear heading, then straight to choosing your course.", tag: "IMPROVED" },
    { item: "Your Recent earnings list on your profile reads at a glance now. It used to repeat \"Daily login +1\" again and again, one row for every day, which buried the earnings you actually want to see. Earnings of the same kind now fold into a single line with a small count and the dates they span, like \"Daily login ×11,\" so your round bonuses and the achievements you've unlocked stand out instead of scrolling past in a blur. A round bonus that used to read \"at null\" where a course name went missing now reads cleanly too.", tag: "IMPROVED" },
    { item: "Your profile stats now mind their grammar. A tile that counts just one of something used to read \"1 Wins\" or \"1 Rounds,\" which always landed a little wrong; it now reads \"1 Win\" and \"1 Round\" when you have exactly one, and ticks back to the plural the moment you have two. A small thing, but the kind of small thing that should just be right.", tag: "IMPROVED" },
    { item: "The Clubhouse chat sits right in its own space now. The box where you type used to float up near the top with a wide stretch of empty room below it, which made the whole page feel half finished, as if something had failed to load. The conversation now fills the screen from the trash talk heading down, and the message box rests at the bottom where your thumb expects it, just above the menu bar, the way every group chat you already use behaves. Open it on an empty day and it still feels settled rather than hollow.", tag: "IMPROVED" },
    { item: "The little handicap trend chart on your profile now keeps an honest scale. The numbers running up its left edge could skip a step, showing something like 23, 22, 21, and then jumping straight to 19, which made the whole graph look uneven and hard to trust. Those markers now climb in even steps every time. And when your handicap has been holding steady, the line rides calmly through the middle of the chart instead of floating up near the top of a half-empty box, so a flat stretch finally reads as the steady play it is.", tag: "FIXED" },
    { item: "The forms you fill out, like setting up a round or saving a note, feel more solid now. The boxes you type into used to sit almost flat against the page, with an edge so soft it was easy to wonder whether they were ready for you. Each one is now gently recessed with a crisper outline, and the box you are typing in lights up with a clear gold ring, so there is never a doubt about where your cursor sits. On the Start a round screen, the Tee it up button is bigger and bolder too, so the main thing to tap is the most obvious thing on the page.", tag: "IMPROVED" },
    { item: "On the scheduling calendar, the three quick buttons under the month now feel like a matched set. Tee Time and Event each had their own warm color, but Range used to sit pale and faded beside them, almost as if it were switched off. Range now wears a deep slate blue, the very color the calendar already uses to mark your range days, so all three read as equal ways to plan your golf.", tag: "IMPROVED" },
    { item: "Every course in your directory now has its own look. Courses without a photo used to share one dark stock picture, so the whole list felt like the same square repeated down the page. Now each one wears its own warm Clubhouse tile with its initials, and it stays that same color every time you visit, so the courses are easy to tell apart at a glance. That same little crest carries onto the course's own page too, so a place you've come to know always greets you the same way.", tag: "IMPROVED" },
    { item: "When you add Parbaughs to your home screen, its launch screen and the status bar across the top now wear the same warm Clubhouse cream as the app itself. Before, they came up in an old dark navy that flashed against the light app as it opened. Now it feels like one piece from the moment you tap the icon.", tag: "IMPROVED" },
    { item: "Updates now reach your phone the next time you open the app. The main part of the app's code could get quietly held onto by your phone after we shipped a change, so a fix or new feature might not actually show up for a long while, even though the app looked up to date. We changed how each new version of that code is named so your phone always picks up the latest on its own, with nothing to reinstall and no cache to clear.", tag: "INFRA" },
    { item: "Round scores read kinder now, and the same way everywhere. Your score shows as a clean number with a small tag beside it telling you how you did against par, like E, +6, or -1. A round under par or right at it gets a quiet green tag, and everything else stays neutral, so a high number is never painted in alarm red. This now holds across the feed, the calendar, a round's own page, a member's profile, the scramble team cards, the course leaderboards, and the image you save to share. The round page and the share card used to show an odd figure that disagreed with the to-par number shown right beside them, and a few other spots still tinted a higher score red; those are gone too.", tag: "IMPROVED" },
    { item: "During a live round, the bar along the bottom of the screen is now clearly the main place to act: move between holes with Prev and Next, and wrap up with Finish. The Finish button that also sits in the scorecard area is now a quieter backup, so there is one obvious set of controls instead of two competing green buttons.", tag: "IMPROVED" },
    { item: "Your round's format now reads with its proper name wherever it shows up. The live scoring screen used to label a Stableford round with the lowercase tag \"stableford,\" and your home dashboard could read \"STABLEFORD PLAY\" or \"BESTBALL PLAY.\" Now the live round, your home card, and the feed all say the same clean name, like Stableford, Best Ball, Match Play, or Skins.", tag: "IMPROVED" },
    { item: "When you start a round, the Format and Holes pickers now show a small down arrow, so it's clear you can tap them to switch things up. Before, they looked like fixed labels, and it wasn't obvious you could change your Format to Stableford, Match, or Skins, or drop to a nine-hole round. They read as the buttons they always were now.", tag: "IMPROVED" },
    { item: "On a phone, the buttons at the bottom of a live round (Previous hole, Next hole, and Finish) now respond every time. The app's main tab bar could sit right on top of them and quietly catch your taps, so moving between holes or finishing up could feel stuck. During a round the main tabs now step aside, leaving the round's own controls clear and tappable, and they slide back the moment you leave the round.", tag: "FIXED" },
    { item: "When you reopen the app, your home screen now loads reliably on the very first try. Once in a while, on a fresh start or a slower connection, it could come up blank for a moment and only a full reload would bring it back. The app now waits for everything it needs before settling on your home view, so you land on the Clubhouse every time.", tag: "FIXED" },
    { item: "The little connection light at the very bottom of the screen now looks after itself. If your signal dropped for a moment (an elevator, a dead spot, a quick hiccup), it could get stuck reading \"Offline\" even after you were clearly back online, and only fully reloading the app would clear it. Now it quietly re-checks the moment you return to the app or your connection comes back, and flips itself to \"Live\" on its own.", tag: "FIXED" },
    { item: "On your home dashboard, the small handicap trend chart used to read \"0 of 3 rounds logged\" even when you clearly had rounds on the books. That little chart only counts recent rounds that factor into your handicap and skips scrambles, so the old wording made it sound like you had not played at all. It now reads \"no rounds in this range,\" or how many of the three it has so far, so it matches the rounds count sitting right beside it.", tag: "IMPROVED" },
    { item: "In the Trophy Room, every badge you've earned now reads as a small lit medallion with a soft brass glow, while the ones still to come sit as quiet recessed slots, so a glance tells you what you've won and what is left to chase. On the Standings ladder, a very long name now trims neatly with an ellipsis, keeping the YOU chip and your round stats in view instead of stretching a row out of line.", tag: "IMPROVED" },
    { item: "If your profile wasn't finished yet, the \"Complete Your Profile\" nudge could quietly pile up into a stack of duplicate notifications over time. It now appears just once and waits there until you fill in your bio, scoring range, and home course. Behind the scenes, the app's allow-list for permitted external frames was tightened and the release safety-checks that confirm your home screen loads cleanly on iPhone and Android are reliable again.", tag: "FIXED" },
    { item: "Commissioners can now build a tournament right inside the app. Pick a format, a game type, a team style, and how points are scored, or start from the classic Smoky Mountain Open setup, then name the event and the title its winner will carry. The app reads everyone's handicap and recent form to draft the matchups and scoring for you, with no outside service involved, and once you lock it in before the first tee the field and the rules are set. Everyone else gets a clean live leaderboard, a form guide before play begins, and a champion card once it's done.", tag: "NEW" },
    { item: "The feed now groups your league's activity by when it happened. As you scroll, quiet date headers like Today, Yesterday, and This Week mark where each stretch begins, so a long run of rounds reads as a clear timeline instead of one endless list.", tag: "IMPROVED" },
    { item: "The Trophy Room reads clearly now. The achievements you've earned sit in cards with a soft gold outline and a gentle lift, and the ones still to come show as clean, readable slots instead of fading into the page. The title ladder at the bottom got the same treatment, so upcoming titles are easy to read rather than nearly invisible.", tag: "IMPROVED" },
    { item: "During a live round you can now fix a hole's par or yardage on the spot when the course record looks wrong: tap Adjust on the scoring screen, nudge the par or type in the yards, and it applies to just that round. Your front-nine and back-nine totals, fairways hit, and handicap math all recompute from the number you set, while the course record itself stays untouched.", tag: "NEW" },
    { item: "Behind the scenes: the app now refuses to be loaded inside another website's frame, a standard protection that stops a hidden page from tricking you into tapping things, and the team added a single security sweep we run every cycle to keep credentials out of the code and catch known issues early.", tag: "INFRA" },
    { item: "On the Season Recap, anyone who has only played nine-hole or scramble rounds used to show the word \"null\" where an eighteen-hole scoring average would normally sit. Those spots now show a simple dash, matching how the Standings page already handles it, so every line in the final standings and the champion card reads cleanly.", tag: "FIXED" },
    { item: "The Caddy's little italic notes on your round history, and the short story under each hole-in-one on the Ace Wall, now read as clean italic text instead of carrying a small colored line down the left edge. It is a quiet touch that brings those two spots in line with the single, even outline the rest of the app already uses.", tag: "IMPROVED" },
    { item: "If you use a screen reader like VoiceOver or TalkBack, the menu now reads correctly. On a larger screen the side menu is announced as the navigation it is, and on a medium screen the slide-in menu is announced as a pop-up only while it is actually open. Before, the side menu could be hidden from the screen reader by mistake.", tag: "FIXED" },
    { item: "The boxes you type into, like the sign-in fields and the spots where you add a comment or send a message, now have a clear outline and a lighter fill, so they read as ready to type in instead of looking switched off. Tapping into one shows a soft gold ring so you always know where you are.", tag: "IMPROVED" },
    { item: "You can now block another member from their profile. Once blocked, you stop seeing their posts, comments, and messages anywhere in the app, and you can unblock them anytime from Settings. Reporting a member is cleaner too: you pick a reason from a tidy list and it goes privately to the Commissioner, instead of the old typed-number popup.", tag: "NEW" },
    { item: "When an action can't go through, like posting a wager, saving an event, or sending a message, the app now explains it in plain language and points you to the fix (for example that you appear to be offline, or that you don't have permission), instead of flashing a confusing technical error.", tag: "IMPROVED" },
    { item: "Your Records page now counts Courses Played correctly: it tallies every distinct course you've actually logged a round at, so the number is right even before anyone fills in the course directory by hand. It used to read zero until courses were added manually.", tag: "FIXED" },
    { item: "Two small clean-ups: the Ace Wall no longer shows a stray line of placeholder text under your hole-in-ones, and the Courses page now invites you to find your course from thousands worldwide in plain language instead of naming the data service behind it.", tag: "IMPROVED" },
    { item: "When a list can't load right now, like the Rich List, your open rounds, or feed comments, the app now shows a clear note and a Try again button instead of a vague \"Failed to load\" line. One tap re-checks without leaving the page.", tag: "IMPROVED" },
    { item: "The example tee times shown before anyone has posted one match the look used on Challenges, Bounties, and Wagers, so the example ideas across all four pages read as one consistent style.", tag: "IMPROVED" },
    { item: "When you haven't logged a round yet, the Rounds page now greets you properly: a clean golf-flag mark, a note that your first round earns 100 XP and the First Blood badge, and a quick tap to start playing, instead of a single plain line of text.", tag: "IMPROVED" },
    { item: "The What's New card on the More page now uses a clear, evergreen line that always points you to these Caddy Notes, instead of an old fixed blurb that no longer matched recent updates.", tag: "IMPROVED" },
    { item: "The example ideas on the Challenges, Bounty Board, and Wagers pages read clearly: each sits on its own clean raised row instead of a faded fill that made them look switched off.", tag: "IMPROVED" },
    { item: "Deleting your account is now a careful, honest flow: we ask for your password and have you type the word DELETE to confirm, we check your password first so a wrong one removes nothing, and the screen tells you plainly what gets removed (your profile, photos, and sign-in) and that it cannot be undone.", tag: "IMPROVED" },
    { item: "When you haven't started a Challenge yet, the page now greets you the way the Bounty Board and Wagers do: a clear heading, a few ideas to spark a match, and one tap to begin. The Courses and Party Games pages, the quick search, and the occasional league-wide alert banner also dropped their stray emoji for the same crisp line-art icons the rest of the app uses, so everything looks sharp and reads the same on every phone.", tag: "IMPROVED" },
    { item: "On a wide desktop screen, the whole app now keeps its content in one tidy centered column: the Clubhouse, Feed, your Rounds, Play Now, the Range, messages, settings, and every board and list, instead of stretching the screen wide, so every row, score, and message reads at a glance (no more controls drifting way off across the page). Wide scorecards and the standings, members, and trophy grids still fill the space where it helps.", tag: "IMPROVED" },
    { item: "The Wagers page now welcomes you the way the Bounty Board does: a clear heading, a few example wagers to spark ideas, and one tap to get one going.", tag: "IMPROVED" },
    { item: "Clubhouse posts behave themselves: bounties, wagers, and chat messages no longer flash a phantom error after they actually go through, and a message that truly fails to send now says so.", tag: "IMPROVED" },
    { item: "Caddy's notes in the feed now sit in a softly tinted card, while everyone else's chat wears the same clean full outline as the rest of the app.", tag: "IMPROVED" },
    { item: "Privacy Policy and Terms of Service are now one tap away in Settings, and the privacy policy spells out exactly what we store, what stays opt-in (like location for weather), and what we never touch.", tag: "NEW" },
    { item: "Home greets you by time of day: Good morning / Good afternoon / Good evening / Welcome back.", tag: "IMPROVED" },
    { item: "\"The league this week\" stat strip on the home page: rounds, average, low score, and momentum vs last week.", tag: "NEW" },
    { item: "Your handicap stat now shows a trend arrow when you have 5+ rounds: ▼ improving / ▲ heavier / ● steady.", tag: "IMPROVED" },
    { item: "Round history now shows ±N to par under every score, and a ★ PR badge marks your personal best.", tag: "IMPROVED" },
    { item: "Standings highlights your own row with a soft gold wash + YOU chip, so you can find yourself in the ladder at a glance.", tag: "IMPROVED" },
    { item: "Trophy Room hero gets a warm gold halo behind your level. The moment should feel like a moment.", tag: "IMPROVED" },
    { item: "Members directory groups by tier (Founding Four / Members) with brass eyebrows + counts.", tag: "IMPROVED" },
    { item: "Mobile home now shows a League Pulse: last 3 league activity items right on home.", tag: "NEW" },
    { item: "Course directory + Feed get warmer empty states with clear next-actions.", tag: "IMPROVED" },
    { item: "Activity feed is steadier: rounds logged offline now show up correctly instead of leaving the feed blank until they sync.", tag: "IMPROVED" },
    { item: "Toasts and notifications wear a cleaner full outline instead of a side stripe, so success and error states read clearly at a glance.", tag: "IMPROVED" },
    { item: "More of the app now shares one clean card outline: the handicap callout, league pulse, range sessions, feed cards, and calendar event chips dropped their colored edge-stripes for a single cohesive look.", tag: "IMPROVED" },
    { item: "Copy across the app reads cleaner: toasts, empty states, help text, the Caddy's post-round notes, and the FAQ now use consistent punctuation instead of stray dashes.", tag: "IMPROVED" },
    { item: "Behind the scenes: the app now ships its code compressed, with comments and extra spacing stripped out, so there's less to download and read the first time you open it. It loads a little quicker, especially on a phone.", tag: "INFRA" },
    { item: "Behind the scenes: visual regression suite catches design drift; pre-commit blocks accidental credential leaks; A- app-health floor maintained.", tag: "INFRA" }
  ];

  currentNotes.forEach(function(r) { h += renderEntry(r); });
  h += '</div></div></div>';

  // Past Releases (newest first; each block collapses by default)
  // archiveNotes data lives in caddynotes-archive.js per W1.A5 (AMD-027).
  // The archive file declares `var caddynotesArchive` at module scope.
  var archiveNotes = caddynotesArchive;

  // W1.I3 restructure: limit "Recent updates" to last 3 releases for clarity.
  // Older releases are still in archiveNotes (so version history is preserved)
  // but only the 3 most recent are surfaced in the UI. Members who want deep
  // history can ask The Caddy. Universal content per locked CTO_INTERFACE.md.
  h += '<div class="section"><div class="sec-head"><span class="sec-title">Recent Updates</span></div>';
  h += '<div style="font-size:10px;color:var(--muted);padding:0 16px 8px">The last three ships, in plain language.</div>';
  archiveNotes.slice(0, 3).forEach(function(block) {
    h += '<div class="card" style="margin-bottom:8px;overflow:hidden">';
    h += '<div onclick="var e=this.nextElementSibling;var c=this.querySelector(\'svg\');var open=e.style.display===\'block\';e.style.display=open?\'none\':\'block\';c.style.transform=open?\'rotate(0deg)\':\'rotate(90deg)\';" style="display:flex;justify-content:space-between;align-items:center;cursor:pointer;padding:12px 14px;gap:8px;min-height:48px">';
    h += '<div style="flex:1;min-width:0">';
    h += '<div style="font-size:12px;color:var(--gold);font-weight:600">' + block.version + ' · ' + block.date + '</div>';
    h += '<div style="font-size:11px;color:var(--muted);margin-top:2px">' + block.headline + '</div>';
    h += '</div>';
    h += '<svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="2" style="color:var(--muted);flex-shrink:0;transition:transform .15s ease"><path d="M6 4l4 4-4 4"/></svg>';
    h += '</div>';
    h += '<div style="display:none;padding:0 14px 14px;font-size:12px;color:var(--cream);line-height:1.8;border-top:1px solid var(--border)">';
    block.items.forEach(function(r) { h += renderEntry(r); });
    h += '</div>';
    h += '</div>';
  });
  h += '</div>';

  // What's in the Bag — full feature list
  h += '<div class="section"><div class="sec-head"><span class="sec-title">What\'s in the Bag</span></div>';
  h += '<div class="card"><div class="card-body" style="font-size:12px;color:var(--cream);line-height:1.8">';
  var features = [
    "Invite-only membership with invite codes",
    "Live hole-by-hole scoring (Play Now) with FIR, GIR, putts",
    "Parbaugh Round: real-time shared scorecard",
    "ParCoins in-game currency with 9 earning triggers",
    "Cosmetics Shop: 70+ items (rings, banners, cards, name effects, titles)",
    "Wager Matches: 6 types including Nassau and Beat Their Score",
    "Bounty Board: coin bounties on scores and birdies",
    "Trash Talk: Spotlight of Shame, Victory Lap, Demand a Rematch",
    "Rich List, Power-Ups, Sponsor a Hole, Name a Tournament",
    "3 formal seasons per year (Spring, Summer, Fall) with awards",
    "Trophy Room: 50+ achievements, XP levels, titles",
    "8 premium themes with background textures and blend modes",
    "Champion Red theme unlocked by winning an event",
    "GHIN World Handicap System calculation",
    "Activity feed with filtering (All/Rounds/Chat/Range)",
    "Clubhouse: group chat with likes, comments, replies",
    "Direct messages between members",
    "Tee time posting with RSVP",
    "Full calendar with event dots and scheduling",
    "30,000+ course search via GolfCourseAPI",
    "Range session timer with drill tracking",
    "Scramble team management with W-L records",
    "Shareable scorecard images in your active theme",
    "Push notifications (FCM)",
    "PWA: installable to home screen",
    "First-time onboarding with profile setup wizard",
    "Commissioner admin panel",
    "Score attestation system for events",
    "Season recap and yearly awards ceremony",
    "Party games linked to active rounds",
    "Pull-to-refresh, skeleton loading, number animations"
  ];
  features.forEach(function(f) {
    h += '<div style="padding:2px 0;display:flex;gap:8px;align-items:flex-start"><span style="color:var(--gold);flex-shrink:0;margin-top:4px"><svg viewBox="0 0 16 16" width="8" height="8" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 8l3 3 7-7"/></svg></span><span>' + f + '</span></div>';
  });
  h += '</div></div></div>';

  // W1.I3 restructure: "Coming Soon" trimmed to a vague forward-looking
  // teaser (4 plain-language directions, no leaks of unshipped specifics).
  // Cumulative inventory lives in "What's in the Bag" above; this section
  // is intentionally light on detail per locked governance.
  h += '<div class="section"><div class="sec-head"><span class="sec-title" style="color:var(--muted)">On the Range</span></div>';
  h += '<div style="font-size:10px;color:var(--muted);padding:0 16px 8px">A few directions we\'re heading. Details land here when they\'re real.</div>';
  h += '<div class="card"><div class="card-body" style="font-size:12px;color:var(--muted);line-height:1.8">';
  var upcoming = [
    "Sharper Clubhouse polish, page by page.",
    "More ways to play together: scrambles, party games, trips.",
    "ParCoins economy continues to grow, earn while you play.",
    "Mobile app on the way for the founding 20."
  ];
  upcoming.forEach(function(u) {
    h += '<div style="padding:2px 0;display:flex;gap:8px;align-items:flex-start"><span style="color:var(--muted2);flex-shrink:0;margin-top:4px"><svg viewBox="0 0 16 16" width="8" height="8" fill="none" stroke="currentColor" stroke-width="1.5"><circle cx="8" cy="8" r="6"/></svg></span><span>' + u + '</span></div>';
  });
  h += '</div></div></div>';

  h += '<div style="text-align:center;padding:16px;font-size:10px;color:var(--muted2)">Built by The Commissioner · v' + APP_VERSION + '</div>';

  document.querySelector('[data-page="caddynotes"]').innerHTML = h;
});
